title: Tangli Ge

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Last updated on Oct 1, 2022."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "research"
 - name: "Teaching"
   link: "teaching"
 - name: "Activities"
   link: "activities"

